---
driver:
  name: vagrant
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero
  always_update_cookbooks: true
  client_rb:
    audit_mode: :audit_only

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[audit-cis::ubuntu1404-100]
  - name: centos-7.2
    run_list:
      - recipe[audit-cis::centos7-100]

suites:
  - name: default

    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
